--create database sport
--drop database sport
--use sport;
--create table( igrac
--sifra int
--ime varchar(50),
--prezime varchar (50),
--datum_rodjenja datatime,
--pozicija datetime,
--broj dresa datatime,
--klub varchar(50),
--);
-- create table (trener
--sifra int,
--ime varchar(50),
--prezime varchar (50),
--datum_rodjenja datatime,
--pozicija datatime,
--klub (varchar),

--create table(klub
--sifra int,
--naziv varchar(50),
--osnovan datatime,
--stadion varchar(50),
--predsjednik varchar(50),
--drzava varchar (50),
--liga varchar(50),
--);


